### ISSUE TITLE
Hi 👋 just introducing myself

### ISSUE THREAD

**Issue by daxaxelrod** [Merpster456/FBLA_Quiz#1]
Hey Ryan,

I’ll be judging your project for FBLA. Lucky for you, I have a Mac! I appreciate your detailed readme, can tell you’ve worked hard on this project. I’ll be doing a deeper dive in the coming weeks and will be posting my thoughts here as well as through official FBLA channels. 

Just a quick note on your command line start, you can simplify a lot here! If you git clone the repo you can into a folder with the name you want

```bash
git clone https://github.com/Merpster456/FBLA_Quiz FBLA_Quiz-master
```

Will copy the project into the correct folder. Then you can just cd it, chmod it and you’re ready to rock and roll. 

Again great work and talk soon! Also, there’s a new GitHub feature called “discussions” which is much better suited for discussions like this, you just have to enable it for the repo. 

Best,
David

**Comment by Merpster456** [comment]
Hey David,

Sorry for such a late reply! Thank you for your advice, I completely looked over the option of renaming the directory and will implement it into the readme as soon as I'm done writing this. Also I will enable the discussions feature as you suggested. I hope you are enjoying my program, and look forward to hearing more from you in the future!

Warm regards,
Ryan
